### ISSUE TITLE
BungeeCord crashing on launch

### ISSUE THREAD

**Issue by fyrekitten** [CaenJones/EaglercraftX-1.19-Server#5]
**Describe the bug**

Bungeecord is crashing after loading ViaVersino

**To Reproduce**
1. Go to 'Bungee folder'
2. Click on 'bungee.bat'
3. See error

**Expected behavior**

Bungeecord launchers and I am able to join server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11, tiny11 23h1]
 - Browser [chrome]
 - Version [latest]

No phone is being used here

**Additional context**

I am using Tiny11, latest release as of 5/8/24

LOG: 

Starting Bungee...
20:28:05 [INFO] Using standard Java JCE cipher.
20:28:05 [INFO] Using standard Java compressor.
20:28:05 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:18eae8a:1842
20:28:06 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())

20:28:06 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource()) 
20:28:06 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource()) 
20:28:06 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource()) 
20:28:06 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())

20:28:06 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())

20:28:06 [INFO] Loaded plugin ViaVersion version 4.9.3 by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv
20:28:06 [INFO] Loaded plugin ViaRewind version 3.0.6 by null
20:28:06 [INFO] [EaglercraftXBungee] Loading vanilla profile: lax1dude
20:28:06 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.3-SNAPSHOT:18eae8a:1842 by SpigotMC
20:28:06 [INFO] Loaded plugin cmd_find version git:cmd_find:1.20-R0.3-SNAPSHOT:18eae8a:1842 by SpigotMC
20:28:06 [INFO] Loaded plugin cmd_kick version git:cmd_kick:1.20-R0.3-SNAPSHOT:18eae8a:1842 by SpigotMC
20:28:06 [INFO] Loaded plugin cmd_server version git:cmd_server:1.20-R0.3-SNAPSHOT:18eae8a:1842 by SpigotMC
20:28:06 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.20-R0.3-SNAPSHOT:18eae8a:1842 by SpigotMC
20:28:06 [INFO] Loaded plugin cmd_send version git:cmd_send:1.20-R0.3-SNAPSHOT:18eae8a:1842 by SpigotMC
20:28:06 [INFO] Loaded plugin ViaBackwards version 4.9.2 by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
20:28:06 [INFO] Loaded plugin cmd_list version git:cmd_list:1.20-R0.3-SNAPSHOT:18eae8a:1842 by SpigotMC
20:28:06 [WARNING] :>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>
20:28:06 [WARNING] :>
20:28:06 [WARNING] :>      EAGLERCRAFTXBUNGEE WARNING:
20:28:06 [WARNING] :>
20:28:06 [WARNING] :>  This plugin wasn't tested to be 'working'
20:28:06 [WARNING] :>  with ANY version of BungeeCord (and forks)
20:28:06 [WARNING] :>  apart from the versions listed below:
20:28:06 [WARNING] :>
20:28:06 [WARNING] :>  - BungeeCord: 1.20-R0.3-SNAPSHOT:67c65e0:1828
20:28:06 [WARNING] :>  - Waterfall: 1.20-R0.3-SNAPSHOT:da6aaf6:572
20:28:06 [WARNING] :>
20:28:06 [WARNING] :>  This is not a Bukkit/Spigot plugin!
20:28:06 [WARNING] :>
20:28:06 [WARNING] :>  Use "-Deaglerxbungee.stfu=true" to hide
20:28:06 [WARNING] :>
20:28:06 [WARNING] :>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>:>
20:28:07 [INFO] [EaglercraftXBungee] Loaded vanilla profile: lax1dude
20:28:07 [INFO] Loaded plugin EaglercraftXBungee version 1.1.0 by lax1dude
20:28:07 [WARNING] Forced host server pvp is not defined
20:28:07 [WARNING] MinecraftForge support is currently unmaintained and may have unresolved issues. Please use at your own risk.
20:28:08 [INFO] [EaglercraftXBungee] Loaded certificate: C:\Users\FyreFunRealm\Desktop\Eag\bungee\plugins\EaglercraftXBungee\eagcert\$dl.11da5ec1e9d8efe3fa0e9998b0c264f5c8cb155f.cert
20:28:08 [INFO] [ViaVersion] Loading block connection mappings ...
20:28:09 [INFO] [ViaBackwards] Loading translations...
20:28:09 [INFO] [EaglercraftXBungee] Loaded certificate: C:\Users\FyreFunRealm\Desktop\Eag\bungee\plugins\EaglercraftXBungee\eagcert\$dl.24a1bafc15c675276968d78cdcb55a04992bddb0.cert
20:28:09 [INFO] [ViaBackwards] Registering protocols...
Detected Bungeecord in crashed/stopped state!
Restarting...

**Comment by CaenJones** [comment]
Hello! if you are using Tiny11 as a host, it is recommended you use the shellscript to launch the server as wine may be causing issues.

**Comment by fyrekitten** [comment]
Tiny11 is windows 11 but stripped down. Should I try on Ubuntu?

**Comment by CaenJones** [comment]
Yea, I would recommend you try ubuntu

**Comment by stpv221** [comment]
Happens to me on the server. I can join, but I can't run commands in the console. running on codespaces @CaenJones

**Comment by PlurrYT-Kolama** [comment]
Same ^^^

**Comment by PlurrYT-Kolama** [comment]
Anyways they pushed PR what fixed it ig

**Comment by stpv221** [comment]
ye
