### ISSUE TITLE
Critical Server bug, Critical Client bug

### ISSUE THREAD

**Issue by RealPlurr** [CaenJones/EaglercraftX-1.19-Server#7]
**Describe the bug**
Server Bug: After installing latest java and starting server server will always auto restart non stoply until modifications in .bat file. Also this result in disk destruction beacuse each restart new crash report/log creates.

Client Bug: No 1.19 items or 1.19 Structures. (Some of them works buggy some of them just not existing including netherite)

**To Reproduce**
Steps to reproduce the behavior: (Server Bug)
1. Download latest OpenJDK Java
2. Start .bat file
3. See how it infinitely restarts
Steps to reproduce the behavior: (Client Bug)
1. Download web version of launcher
2. Start it and join any 1.19 server (In my situation wss://vanilaplay.plurryt.uk.to)
3. And see how it generated structures but you wont he able interact usually with "new" villagers or you wont be able to get new items. Same including water you wont be able to swim in water like in 1.13+.

**Expected behavior**
Server bug: No auto restarts for no reason (just recode .bat file)
Client bug: Working item's and working structures + items in single player.

**Screenshots**
I will place screenshots about server bug a bit later. 
About client bug I dont know what screenshot do you need.

**Desktop (please complete the following information):**
Server:
 - OS: Windows Server 2019
 - Browser: Edge for Servers / Chrome
 - Version: Latest
Client:
 - OS: Windows 11
 - Browser: Edge/Chrome
 - Version: Latest

**Smartphone:** Didn't used to get/find bug.

**Additional context**
Just fix it..

**Comment by CaenJones** [comment]
Heya! Thanks so much for the issue and PR! I have merged your fix for the `.bat` file and will also address the `.sh` file if needed. As  for correct textures, and interactions. I am working on a plugin to port more of this to the 1.8 clients. Should be available in a month or so.

**Comment by CaenJones** [comment]
Oh, and thank you so much for the 1.19 plugin compatibility update!

**Comment by PlurrYT-Kolama** [comment]
Hello! I fixed plugins here is link to repo: https://vanilagit.plurryt.uk.to/PlurrYT/VanilaPlex-LTS
I hope its okay if ill take your project and will try to remake it to get even better performance and do real 1.19 support;)

**Comment by CaenJones** [comment]
ofc! that is what FOSS is for! :)

**Comment by CaenJones** [comment]
gonna have trouble with the "real support" thing tho xD

**Comment by PlurrYT-Kolama** [comment]
true true | tea vm will never allow that eh
